---
name: Arduino_CI

on: [push, pull_request]

jobs:
  arduino_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Di-Strix/arduino-ci-action@master
        env:
          EXPECT_EXAMPLES: true
          CUSTOM_INIT_SCRIPT: install_dependencies.sh